spring:
    datasource:
        url: jdbc:mariadb://mydb1.c382ogcea5iw.us-east-1.rds.amazonaws.com
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: 12312312

