spring:
    datasource:
        url: jdbc:mariadb://mydb1.c382ogcea5iw.us-east-1.rds.amazonaws.com:3306/mydatabase
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: 12312312
   

    
# spring:
#     datasource:
#         url: jdbc:h2:mem:testdb
#         driver-class-name: org.h2.Driver
#         username: sa
#         password: 
#     jpa:
#         database-platform: org.hibernate.dialect.H2Dialect

